# Generated by Django 4.2.8 on 2023-12-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionResponsibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="action",
            name="responsibility",
            field=models.ManyToManyField(
                editable=False,
                related_name="actions",
                to="actions.actionresponsibility",
            ),
        ),
    ]
