# Generated by Django 4.2.8 on 2023-12-15 00:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0003_remove_action_responsibility_action_responsibility"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Action",
        ),
        migrations.DeleteModel(
            name="ActionResponsibility",
        ),
    ]
