# Generated by Django 4.2.6 on 2023-10-31 03:49

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0002_alter_riskfactor_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributingfactor",
            name="factors",
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(
                blank=True, null=True
            ),
        ),
    ]
