# Generated by Django 4.2.7 on 2023-11-15 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0006_rename_riskfactor_riskcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContributingFactorStandardControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revisit_in_implementation_plan", models.BooleanField(default=False)),
                (
                    "contributing_factor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contributing_factor_standard_controls",
                        to="risk.contributingfactor",
                    ),
                ),
                (
                    "standard_control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contributing_factor_standard_controls",
                        to="risk.standardcontrol",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contributingfactor",
            name="standard_controls",
            field=models.ManyToManyField(
                related_name="contributing_factors",
                through="risk.ContributingFactorStandardControl",
                to="risk.standardcontrol",
            ),
        ),
    ]
