# Generated by Django 4.2.7 on 2023-11-16 03:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0008_alter_contributingfactorstandardcontrol_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="overwritecontrol",
            options={
                "verbose_name": "Control (Overwrite)",
                "verbose_name_plural": "Controls (Overwrite)",
            },
        ),
        migrations.AlterModelOptions(
            name="standardcontrol",
            options={
                "verbose_name": "Control (Standard)",
                "verbose_name_plural": "Controls (Standard)",
            },
        ),
    ]
