# Generated by Django 4.2.7 on 2023-11-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0010_consequence_likelihood_risklevel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="likelihood",
            name="lower_bound",
        ),
        migrations.RemoveField(
            model_name="likelihood",
            name="upper_bound",
        ),
        migrations.AddField(
            model_name="likelihood",
            name="ordinal_scale",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
