# Generated by Django 4.2.7 on 2023-11-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0011_remove_likelihood_lower_bound_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="risklevel",
            name="ordinal_scale",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="likelihood",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="risklevel",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="likelihood",
            unique_together={("name", "ordinal_scale")},
        ),
        migrations.AlterUniqueTogether(
            name="risklevel",
            unique_together={("name", "ordinal_scale")},
        ),
    ]
