# Generated by Django 4.2.7 on 2023-11-17 01:17

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0013_riskrating"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Control (Additional)",
                "verbose_name_plural": "Controls (Additional)",
            },
        ),
    ]
