# Generated by Django 4.2.7 on 2023-11-17 03:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0014_additionalcontrol"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="riskrating",
            unique_together={("consequence", "likelihood")},
        ),
    ]
