# Generated by Django 4.2.7 on 2023-11-21 01:24

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0015_alter_riskrating_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributingfactorstandardcontrol",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="contributingfactorstandardcontrol",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
    ]
