# Generated by Django 4.2.7 on 2023-11-28 06:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0018_alter_riskrating_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="likelihoodofconsequence",
            unique_together={("consequence", "likelihood")},
        ),
    ]
