# Generated by Django 4.2.11 on 2024-03-08 03:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messagebatch",
            options={
                "verbose_name": "Message Batch",
                "verbose_name_plural": "Message Batches",
            },
        ),
        migrations.AlterField(
            model_name="messagebatch",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)smessage_batches", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="messagebatch",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)smessage_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
