# Generated by Django 4.2.6 on 2023-11-03 02:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("operationalplanning", "0005_legalapproval_approval_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="legalapproval",
            old_name="can_provide_evidence",
            new_name="has_additional_permissions",
        ),
    ]
