# Generated by Django 4.2.6 on 2023-11-07 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_auto_load_lgas"),
        ("operationalplanning", "0009_operationalarea_mitigation_purpose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationalareaapproval",
            name="lga",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operationalareaapprovals",
                to="main.lga",
                verbose_name="Shire/LGA",
            ),
        ),
    ]
