# Generated by Django 4.2.6 on 2023-11-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "operationalplanning",
            "0014_operationalplan_operationalplanapproval_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationalplan",
            name="operational_area_different_from_bpu_rationale",
        ),
        migrations.AddField(
            model_name="operationalarea",
            name="operational_area_different_from_bpu_rationale",
            field=models.TextField(blank=True, null=True),
        ),
    ]
