# Generated by Django 4.2.6 on 2023-11-09 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_auto_load_lgas"),
        (
            "operationalplanning",
            "0015_remove_operationalplan_operational_area_different_from_bpu_rationale_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationalarea",
            name="mitigation_purpose",
        ),
        migrations.RemoveField(
            model_name="operationalplan",
            name="contentious_burn",
        ),
        migrations.RemoveField(
            model_name="operationalplan",
            name="contentious_rationale",
        ),
        migrations.AddField(
            model_name="operationalarea",
            name="contentious_burn",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="operationalarea",
            name="contentious_rationale",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationalarea",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operational_areas",
                to="main.district",
            ),
        ),
        migrations.AddField(
            model_name="operationalarea",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operational_areas",
                to="main.region",
            ),
        ),
        migrations.AddField(
            model_name="operationalplan",
            name="operation",
            field=models.CharField(
                choices=[
                    ("burning", "Burning"),
                    ("mechanical", "Stand-alone Mechanical"),
                ],
                default="burning",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="operationalplan",
            name="operational_intent",
            field=models.TextField(blank=True, null=True),
        ),
    ]
