# Generated by Django 4.2.6 on 2023-11-09 04:21

import django.core.validators
from django.db import migrations, models
import govapp.apps.main.models


class Migration(migrations.Migration):
    dependencies = [
        ("operationalplanning", "0017_remove_operationalarea_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalplan",
            name="window_of_opportunity",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="operationalplan",
            name="burn_priority",
            field=govapp.apps.main.models.IntervalIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
