# Generated by Django 4.2.7 on 2023-11-10 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "operationalplanning",
            "0021_remove_objectiveandsuccesscriteria_success_criteria_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="objective",
            options={
                "verbose_name": "Objective and Success Criteria - Objective",
                "verbose_name_plural": "Objective and Success Criteria - Objectives",
            },
        ),
        migrations.AlterModelOptions(
            name="objectiveandsuccesscriteria",
            options={
                "verbose_name": "Objective and Success Criterion",
                "verbose_name_plural": "Objective and Success Criteria",
            },
        ),
        migrations.AlterModelOptions(
            name="successcriteria",
            options={
                "verbose_name": "Objective and Success Criteria - Success Criterion",
                "verbose_name_plural": "Objective and Success Criteria - Success Criteria",
            },
        ),
        migrations.AlterModelOptions(
            name="successcriteriacomparisonoperator",
            options={
                "verbose_name": "Objective and Success Criteria - Success Criterion Comparison Operator",
                "verbose_name_plural": "Objective and Success Criteria - Success Criterion Comparison Operators",
            },
        ),
        migrations.AlterModelOptions(
            name="successcriterialeftvalue",
            options={
                "verbose_name": "Objective and Success Criteria - Success Criterion Left Value",
                "verbose_name_plural": "Objective and Success Criteria - Success Criterion Left Values",
            },
        ),
        migrations.AlterField(
            model_name="successcriteria",
            name="objective_and_success_criteria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="success_criteria",
                to="operationalplanning.objectiveandsuccesscriteria",
            ),
        ),
    ]
