# Generated by Django 4.2.7 on 2023-11-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operationalplanning", "0022_alter_objective_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legalapproval",
            name="approval_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("endorsement", "Endorsement"),
                    ("approval", "Approval"),
                    ("endorsement_or_approval", "Endorsement/Approval"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
