# Generated by Django 4.2.6 on 2023-11-10 02:23

from django.core.management import call_command
from django.db import migrations


fixtures_path = "govapp/apps/operationalplanning/fixtures/"


def load_legalapprovals(apps, schema_editor):
    call_command("loaddata", fixtures_path + "legalapprovals.json", verbosity=0)


class Migration(migrations.Migration):
    dependencies = [
        ("operationalplanning", "0023_alter_legalapproval_approval_type"),
    ]

    operations = [
        migrations.RunPython(load_legalapprovals, atomic=True),
    ]
