# Generated by Django 4.2.7 on 2023-11-14 04:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import govapp.apps.main.models


class Migration(migrations.Migration):
    dependencies = [
        ("operationalplanning", "0023_alter_legalapproval_approval_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuccessCriteriaReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("achieved", "Achieved"),
                            ("not_achieved", "Not Achieved"),
                            ("not_ started", "Not Started"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "result_achieved_ratio",
                    govapp.apps.main.models.IntervalFloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Objective and Success Criteria - Success Criterion Report",
                "verbose_name_plural": "Objective and Success Criteria - Success Criterion Reports",
            },
        ),
        migrations.AddField(
            model_name="successcriteria",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="successcriteria",
                to="operationalplanning.successcriteriareport",
            ),
        ),
    ]
