# Generated by Django 4.2.7 on 2023-11-14 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("operationalplanning", "0025_successcriteriareport_successcriteria_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="successcriteria",
            name="report",
        ),
        migrations.AddField(
            model_name="successcriteriareport",
            name="success_criteria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="successcriteriareports",
                to="operationalplanning.successcriteria",
            ),
        ),
    ]
