# Generated by Django 4.2.7 on 2023-11-15 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("traffic", "0004_remove_road_traffic_traffic_roads"),
        ("operationalplanning", "0026_remove_successcriteria_report_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalplan",
            name="traffic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operational_plans",
                to="traffic.traffic",
            ),
        ),
    ]
