# Generated by Django 4.2.7 on 2023-11-15 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0004_remove_riskfactor_contributing_factor_and_more"),
        ("operationalplanning", "0028_alter_successcriteriareport_result"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OperationalAreaRiskFactor",
            new_name="OperationalPlanRiskFactor",
        ),
        migrations.RemoveField(
            model_name="operationalplanriskfactor",
            name="operational_area",
        ),
        migrations.AddField(
            model_name="operationalplanriskfactor",
            name="operational_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="operationalplanning.operationalplan",
            ),
        ),
    ]
