# Generated by Django 4.2.7 on 2023-11-15 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        # ("risk", "0005_standardcontrol"),
        ("risk", "0006_rename_riskfactor_riskcategory"),
        (
            "operationalplanning",
            "0029_rename_operationalareariskfactor_operationalplanriskfactor_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalPlanRiskCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("values_affected", models.TextField(blank=True, null=True)),
                (
                    "contributing_factor",
                    models.ManyToManyField(
                        editable=False,
                        related_name="risk_categories",
                        to="risk.contributingfactor",
                    ),
                ),
                (
                    "operational_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operationalplanning.operationalplan",
                    ),
                ),
                (
                    "risk_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="risk.riskcategory",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="OperationalPlanRiskFactor",
        ),
    ]
