# Generated by Django 4.2.7 on 2023-11-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0006_rename_riskfactor_riskcategory"),
        (
            "operationalplanning",
            "0031_remove_operationalplanriskcategory_contributing_factor_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationalplanriskcategory",
            name="values_affected",
        ),
        migrations.AddField(
            model_name="operationalplanriskcategory",
            name="contributing_factor",
            field=models.ManyToManyField(
                editable=False,
                related_name="risk_categories",
                through="operationalplanning.OperationalPlanRiskCategoryContributingFactor",
                to="risk.contributingfactor",
            ),
        ),
        migrations.AddField(
            model_name="operationalplanriskcategorycontributingfactor",
            name="values_affected",
            field=models.TextField(blank=True, null=True),
        ),
    ]
