# Generated by Django 4.2.7 on 2023-11-16 04:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0009_alter_overwritecontrol_options_and_more"),
        (
            "operationalplanning",
            "0033_operationalplanriskcategorycontributingfactorcontroloverwrite_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operationalplanriskcategorycontributingfactorcontroloverwrite",
            options={
                "verbose_name": "Standard Control Overwrite",
                "verbose_name_plural": "Standard Control Overwrites",
            },
        ),
        migrations.AlterUniqueTogether(
            name="operationalplanriskcategorycontributingfactorcontroloverwrite",
            unique_together={
                (
                    "operational_plan_risk_category_contributing_factor",
                    "overwrite_control",
                )
            },
        ),
    ]
