# Generated by Django 4.2.7 on 2023-11-17 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0014_additionalcontrol"),
        ("operationalplanning", "0037_delete_operationalplanriskrating"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalPlanRiskCategoryContributingFactorRiskRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contributing_factor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="operationalplanning.operationalplanriskcategorycontributingfactor",
                    ),
                ),
                (
                    "risk_rating",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="risk.riskrating",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="operationalplanriskcategorycontributingfactor",
            name="risk_ratings",
            field=models.ManyToManyField(
                editable=False,
                related_name="operational_plan_risk_category_contributing_factors",
                through="operationalplanning.OperationalPlanRiskCategoryContributingFactorRiskRating",
                to="risk.riskrating",
            ),
        ),
    ]
