# Generated by Django 4.2.7 on 2023-11-17 02:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "operationalplanning",
            "0038_operationalplanriskcategorycontributingfactorriskrating_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operationalplanriskcategorycontributingfactorriskrating",
            options={
                "verbose_name": "Risk Rating",
                "verbose_name_plural": "Risk Ratings",
            },
        ),
    ]
