# Generated by Django 4.2.7 on 2023-11-17 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0015_alter_riskrating_unique_together"),
        (
            "operationalplanning",
            "0039_alter_operationalplanriskcategorycontributingfactorriskrating_options",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationalplanriskcategorycontributingfactorriskrating",
            name="contributing_factor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operational_plan_risk_category_contributing_factor_risk_ratings",
                to="operationalplanning.operationalplanriskcategorycontributingfactor",
            ),
        ),
        migrations.AlterField(
            model_name="operationalplanriskcategorycontributingfactorriskrating",
            name="risk_rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operational_plan_risk_category_contributing_factor_risk_ratings",
                to="risk.riskrating",
            ),
        ),
    ]
