# Generated by Django 4.2.7 on 2023-11-17 03:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "operationalplanning",
            "0040_alter_operationalplanriskcategorycontributingfactorriskrating_contributing_factor_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationalplanriskcategorycontributingfactor",
            name="risk_ratings",
        ),
        migrations.DeleteModel(
            name="OperationalPlanRiskCategoryContributingFactorRiskRating",
        ),
    ]
