# Generated by Django 4.2.7 on 2023-11-17 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0015_alter_riskrating_unique_together"),
        (
            "operationalplanning",
            "0041_remove_operationalplanriskcategorycontributingfactor_risk_ratings_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalPlanRiskCategoryContributingFactorRiskRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operational_plan_risk_category_contributing_factor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_plan_risk_category_contributing_factor_risk_ratings",
                        to="operationalplanning.operationalplanriskcategorycontributingfactor",
                    ),
                ),
                (
                    "risk_rating",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_plan_risk_category_contributing_factor_risk_ratings",
                        to="risk.riskrating",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Rating",
                "verbose_name_plural": "Risk Ratings",
            },
        ),
        migrations.AddField(
            model_name="operationalplanriskcategorycontributingfactor",
            name="risk_ratings",
            field=models.ManyToManyField(
                editable=False,
                related_name="operational_plan_risk_category_contributing_factors",
                through="operationalplanning.OperationalPlanRiskCategoryContributingFactorRiskRating",
                to="risk.riskrating",
            ),
        ),
    ]
