# Generated by Django 4.2.7 on 2023-11-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "operationalplanning",
            "0042_operationalplanriskcategorycontributingfactorriskrating_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalplanriskcategorycontributingfactorriskrating",
            name="control_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard Control"),
                    ("additional", "Additional Control"),
                ],
                default="standard",
                max_length=255,
            ),
        ),
    ]
