# Generated by Django 4.2.7 on 2023-11-17 07:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "operationalplanning",
            "0044_operationalplanriskcategorycontributingfactor_risk_rating_standard",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="operationalplanriskcategorycontributingfactor",
            old_name="risk_ratings",
            new_name="risk_ratings_additional",
        ),
        migrations.RemoveField(
            model_name="operationalplanriskcategorycontributingfactorriskrating",
            name="control_type",
        ),
    ]
