# Generated by Django 4.2.7 on 2023-11-20 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0015_alter_riskrating_unique_together"),
        (
            "operationalplanning",
            "0045_rename_risk_ratings_operationalplanriskcategorycontributingfactor_risk_ratings_additional_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalPlanRiskCategoryContributingFactorAdditionalControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "additional_control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_plan_risk_category_contributing_factor_additional_control",
                        to="risk.additionalcontrol",
                    ),
                ),
                (
                    "operational_plan_risk_category_contributing_factor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_plan_risk_category_contributing_factor_additional_control",
                        to="operationalplanning.operationalplanriskcategorycontributingfactor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Additional Control",
                "verbose_name_plural": "Additional Controls",
                "unique_together": {
                    (
                        "operational_plan_risk_category_contributing_factor",
                        "additional_control",
                    )
                },
            },
        ),
    ]
