# Generated by Django 4.2.7 on 2023-11-20 07:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0015_alter_riskrating_unique_together"),
        (
            "operationalplanning",
            "0046_operationalplanriskcategorycontributingfactoradditionalcontrol",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OperationalPlanRiskCategoryContributingFactorControlOverwrite",
            new_name="OperationalPlanRiskCategoryContributingFactorOverwriteControl",
        ),
    ]
