# Generated by Django 4.2.7 on 2023-11-20 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0015_alter_riskrating_unique_together"),
        (
            "operationalplanning",
            "0047_rename_operationalplanriskcategorycontributingfactorcontroloverwrite_operationalplanriskcategorycont",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationalplanriskcategorycontributingfactor",
            name="risk_rating_standard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operational_plan_risk_category_contributing_factors_for_standard_controls",
                to="risk.riskrating",
                verbose_name="Risk rating (after application of standard controls)",
            ),
        ),
    ]
