# Generated by Django 4.2.7 on 2023-11-20 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0015_alter_riskrating_unique_together"),
        (
            "operationalplanning",
            "0048_alter_operationalplanriskcategorycontributingfactor_risk_rating_standard",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OperationalPlanRiskCategoryContributingFactorRiskRating",
            new_name="OperationalPlanRiskCategoryContributingFactorAdditionalControlRiskRating",
        ),
        migrations.AlterModelOptions(
            name="operationalplanriskcategorycontributingfactoradditionalcontrolriskrating",
            options={
                "verbose_name": "Risk Rating (after application of additional controls)",
                "verbose_name_plural": "Risk Ratings (after application of additional controls)",
            },
        ),
    ]
