# Generated by Django 4.2.7 on 2023-11-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0015_alter_riskrating_unique_together"),
        (
            "operationalplanning",
            "0049_rename_operationalplanriskcategorycontributingfactorriskrating_operationalplanriskcategorycontributi",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalplanriskcategorycontributingfactor",
            name="additional_controls",
            field=models.ManyToManyField(
                editable=False,
                related_name="operational_plan_risk_category_contributing_factors",
                through="operationalplanning.OperationalPlanRiskCategoryContributingFactorAdditionalControl",
                to="risk.additionalcontrol",
            ),
        ),
    ]
