# Generated by Django 4.2.7 on 2023-11-29 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_neighbourrole_neighbour"),
        (
            "operationalplanning",
            "0050_operationalplanriskcategorycontributingfactor_additional_controls",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Contingency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("suppression_constraints", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Contingency",
                "verbose_name_plural": "Contingencies",
            },
        ),
        migrations.CreateModel(
            name="ContingencyNeighbour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contingency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contingency_neighbours",
                        to="operationalplanning.contingency",
                    ),
                ),
                (
                    "neighbour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contingency_neighbours",
                        to="main.neighbour",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contingency",
            name="neighbours",
            field=models.ManyToManyField(
                related_name="contingencies",
                through="operationalplanning.ContingencyNeighbour",
                to="main.neighbour",
                verbose_name="Neighbouring landowners and significant stakeholders",
            ),
        ),
        migrations.AddField(
            model_name="contingency",
            name="operational_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contingencies",
                to="operationalplanning.operationalplan",
            ),
        ),
    ]
