# Generated by Django 4.2.7 on 2023-11-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operationalplanning", "0051_contingency_contingencyneighbour_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operational_overview", models.TextField(blank=True, null=True)),
                ("ignition_sequence", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Prescription",
                "verbose_name_plural": "Prescriptions",
            },
        ),
    ]
