# Generated by Django 4.2.7 on 2023-11-29 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("operationalplanning", "0052_prescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalplan",
            name="prescription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operational_plans",
                to="operationalplanning.prescription",
            ),
        ),
    ]
