# Generated by Django 4.2.7 on 2023-11-29 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "prescriptiondetails",
            "0002_burnarea_ffdirange_gfdirange_glcrange_pmcrange_and_more",
        ),
        ("operationalplanning", "0053_operationalplan_prescription"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrescriptionFuelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fuel_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_fuel_types",
                        to="prescriptiondetails.fueltype",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_fuel_types",
                        to="operationalplanning.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Burning Prescription Fuel Type",
                "verbose_name_plural": "Burning Prescription Fuel Types",
                "unique_together": {("prescription", "fuel_type")},
            },
        ),
        migrations.AddField(
            model_name="prescription",
            name="fuel_types",
            field=models.ManyToManyField(
                related_name="prescriptions",
                through="operationalplanning.PrescriptionFuelType",
                to="prescriptiondetails.fueltype",
                verbose_name="Fuel Types",
            ),
        ),
    ]
