# Generated by Django 4.2.7 on 2023-12-01 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("prescriptiondetails", "0007_applicablefueltypeprescriptiondetail_and_more"),
        ("operationalplanning", "0055_prescriptionfueltype_burn_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriptionfueltype",
            name="glc_range",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescription_fuel_types",
                to="prescriptiondetails.glcrange",
                verbose_name="Ground Level Concentration (GLC)",
            ),
        ),
        migrations.AlterField(
            model_name="prescriptionfueltype",
            name="pmc_range",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescription_fuel_types",
                to="prescriptiondetails.pmcrange",
                verbose_name="Profile Fuel Moisture Content (PMC)",
            ),
        ),
        migrations.AlterField(
            model_name="prescriptionfueltype",
            name="smc_range",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescription_fuel_types",
                to="prescriptiondetails.smcrange",
                verbose_name="Surface Fuel Moisture Content (SMC)",
            ),
        ),
    ]
