# Generated by Django 4.2.7 on 2023-12-01 07:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_neighbourrole_neighbour"),
        ("operationalplanning", "0057_remove_operationalplan_context_map_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalAreaApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("text_as_approval", models.TextField(blank=True, null=True)),
                ("text_remove_justification", models.TextField(blank=True, null=True)),
                (
                    "legal_approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operationalareaapprovals",
                        to="operationalplanning.legalapproval",
                    ),
                ),
                (
                    "lga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operationalareaapprovals",
                        to="main.lga",
                        verbose_name="Shire/LGA",
                    ),
                ),
                (
                    "operational_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operationalareaapprovals",
                        to="operationalplanning.operationalarea",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Operational Area Legal/Approvals",
                "unique_together": {("operational_area", "legal_approval")},
            },
        ),
    ]
