# Generated by Django 4.2.7 on 2023-12-04 03:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("main", "0013_neighbourrole_neighbour"),
        (
            "operationalplanning",
            "0060_operationalarea_requires_other_land_approval_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationalplan",
            name="legal_approvals",
        ),
        migrations.CreateModel(
            name="ModelLegalApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("text_as_approval", models.TextField(blank=True, null=True)),
                ("text_remove_justification", models.TextField(blank=True, null=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_type",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "legal_approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modellegalapprovals",
                        to="operationalplanning.legalapproval",
                    ),
                ),
                (
                    "lga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modellegalapprovals",
                        to="main.lga",
                        verbose_name="Shire/LGA",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Legal/Approvals",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="operational_content_312160_idx",
                    )
                ],
            },
        ),
    ]
