# Generated by Django 4.2.7 on 2023-12-04 05:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("operationalplanning", "0061_remove_operationalplan_legal_approvals_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="operationalplanapproval",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="operationalplanapproval",
            name="legal_approval",
        ),
        migrations.RemoveField(
            model_name="operationalplanapproval",
            name="lga",
        ),
        migrations.RemoveField(
            model_name="operationalplanapproval",
            name="operational_plan",
        ),
        migrations.DeleteModel(
            name="OperationalAreaApproval",
        ),
        migrations.DeleteModel(
            name="OperationalPlanApproval",
        ),
    ]
