# Generated by Django 4.2.7 on 2023-12-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operationalplanning", "0063_remove_modellegalapproval_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalplan",
            name="requires_other_land_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="operationalplan",
            name="requires_owner_approvals",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="operationalplan",
            name="requires_shire_approvals",
            field=models.BooleanField(default=False),
        ),
    ]
