# Generated by Django 4.2.7 on 2023-12-06 05:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "operationalplanning",
            "0064_operationalplan_requires_other_land_approval_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationalarea",
            name="requires_other_land_approval",
        ),
        migrations.RemoveField(
            model_name="operationalarea",
            name="requires_owner_approvals",
        ),
        migrations.RemoveField(
            model_name="operationalarea",
            name="requires_shire_approvals",
        ),
        migrations.RemoveField(
            model_name="operationalplan",
            name="requires_other_land_approval",
        ),
        migrations.RemoveField(
            model_name="operationalplan",
            name="requires_owner_approvals",
        ),
        migrations.RemoveField(
            model_name="operationalplan",
            name="requires_shire_approvals",
        ),
    ]
