# Generated by Django 4.2.7 on 2023-12-08 03:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "operationalplanning",
            "0066_operationalarea_fauna_authority_to_take_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationalarea",
            name="fauna_authority_to_take",
        ),
        migrations.RemoveField(
            model_name="operationalarea",
            name="flora_authority_to_take",
        ),
    ]
