# Generated by Django 4.2.7 on 2023-12-08 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_neighbourrole_neighbour"),
        (
            "operationalplanning",
            "0067_remove_operationalarea_fauna_authority_to_take_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalplan",
            name="context_map",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.modelfile",
            ),
        ),
    ]
