# Generated by Django 4.2.7 on 2023-12-08 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("legalapproval", "0010_otherapproval"),
        ("operationalplanning", "0069_operationalplan_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationalplan",
            name="fauna_authority_to_take",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_fauna_att",
                to="legalapproval.otherapproval",
                verbose_name="Fauna Authority To Take",
            ),
        ),
        migrations.AlterField(
            model_name="operationalplan",
            name="flora_authority_to_take",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_flora_att",
                to="legalapproval.otherapproval",
                verbose_name="Flora Authority To Take",
            ),
        ),
    ]
