# Generated by Django 4.2.7 on 2023-12-11 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "legalapproval",
            "0014_remove_modellegalapproval_disturbance_approval_and_more",
        ),
        (
            "operationalplanning",
            "0071_alter_operationalplan_fauna_authority_to_take_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalarea",
            name="disturbance_approval",
            field=models.ManyToManyField(
                related_name="%(class)s_das_approvals",
                to="legalapproval.disturbanceapplication",
            ),
        ),
        migrations.AddField(
            model_name="operationalarea",
            name="fauna_authority_to_take",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_fauna_atts",
                to="legalapproval.authoritytotake",
            ),
        ),
        migrations.AddField(
            model_name="operationalarea",
            name="flora_authority_to_take",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_flora_atts",
                to="legalapproval.authoritytotake",
            ),
        ),
        migrations.AddField(
            model_name="operationalplan",
            name="disturbance_approval",
            field=models.ManyToManyField(
                related_name="%(class)s_das_approvals",
                to="legalapproval.disturbanceapplication",
            ),
        ),
    ]
