# Generated by Django 4.2.7 on 2023-12-11 08:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("operationalplanning", "0072_operationalarea_disturbance_approval_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operationalarea",
            old_name="disturbance_approval",
            new_name="disturbance_application",
        ),
        migrations.RenameField(
            model_name="operationalplan",
            old_name="disturbance_approval",
            new_name="disturbance_application",
        ),
    ]
