# Generated by Django 4.2.11 on 2024-03-06 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("operationalplanning", "0076_alter_operationalplan_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationalplan",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
