# Generated by Django 4.2.7 on 2023-11-14 07:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import govapp.apps.main.models
import model_utils.fields
import protected_media.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Traffic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "indicative_traffic_management_scheme",
                    protected_media.models.ProtectedFileField(
                        blank=True,
                        null=True,
                        storage=protected_media.models.ProtectedFileSystemStorage(),
                        upload_to=govapp.apps.main.models.file_upload_location,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Traffic",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Road",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("owner", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "speed",
                    govapp.apps.main.models.IntervalIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(130),
                        ],
                    ),
                ),
                ("shoulder_width", models.FloatField(blank=True, null=True)),
                (
                    "traffic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="traffic.traffic",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Roads",
                "ordering": ["name"],
            },
        ),
    ]
