# Generated by Django 4.2.7 on 2023-11-14 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("traffic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="traffic",
            name="display_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="TrafficGuidanceScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("active_from", models.DateField(blank=True, null=True)),
                ("active_to", models.DateField(blank=True, null=True)),
                ("hyperlink", models.URLField(blank=True, null=True)),
                (
                    "road",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trafficguidanceschemes",
                        to="traffic.road",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Traffic Guidance Schemes",
                "ordering": ["name"],
            },
        ),
    ]
