# Generated by Django 4.2.7 on 2023-11-14 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("traffic", "0002_traffic_display_name_trafficguidancescheme"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name_plural": "Road Owners",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="road",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="roads",
                to="traffic.roadowner",
            ),
        ),
    ]
