# Generated by Django 4.2.7 on 2023-11-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traffic", "0003_roadowner_alter_road_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="road",
            name="traffic",
        ),
        migrations.AddField(
            model_name="traffic",
            name="roads",
            field=models.ManyToManyField(
                blank=True, related_name="traffics", to="traffic.road"
            ),
        ),
    ]
