# Generated by Django 4.2.7 on 2023-11-15 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("traffic", "0004_remove_road_traffic_traffic_roads"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trafficguidancescheme",
            name="road",
        ),
        migrations.AddField(
            model_name="road",
            name="traffic_guidance_scheme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="roads",
                to="traffic.trafficguidancescheme",
            ),
        ),
    ]
