# Generated by Django 4.2.7 on 2023-12-01 02:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traffic", "0006_trafficrequiredarrangement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="traffic",
            name="indicative_traffic_management_scheme",
        ),
    ]
