# Generated by Django 4.2.6 on 2023-10-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_modelfile_delete_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("display_name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("display_name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
