# Generated by Django 4.2.6 on 2023-10-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_district_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="display_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="display_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
