# Generated by Django 4.2.6 on 2023-10-16 02:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aviation", "0011_delete_aviationrequest"),
        ("main", "0005_alter_district_display_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="District",
        ),
    ]
