# Generated by Django 4.2.6 on 2023-10-16 03:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_district"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="district",
            options={"ordering": ["region", "name"]},
        ),
    ]
