# Generated by Django 4.2.6 on 2023-10-16 05:32

from django.core.management import call_command
from django.db import migrations


fixtures_path = 'govapp/apps/main/fixtures/'


def load_regions(apps, schema_editor):
    call_command('loaddata', fixtures_path + 'regions.json', verbosity=0)


def load_districts(apps, schema_editor):
    call_command('loaddata', fixtures_path + 'districts.json', verbosity=0)


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_district_options"),
    ]

    operations = [
        migrations.RunPython(load_regions, atomic=True),
        migrations.RunPython(load_districts, atomic=True),
    ]
