# Generated by Django 4.2.6 on 2023-10-31 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_auto_load_regions_districts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.district"
                    ),
                ),
            ],
            options={
                "ordering": ["district", "name"],
            },
        ),
    ]
