# Generated by Django 4.2.6 on 2023-11-01 03:13

from django.core.management import call_command
from django.db import migrations


fixtures_path = "govapp/apps/main/fixtures/"


def load_lgas(apps, schema_editor):
    call_command("loaddata", fixtures_path + "lgas.json", verbosity=0)


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_alter_lga_options_remove_lga_district"),
    ]

    operations = [
        migrations.RunPython(load_lgas, atomic=True),
    ]
