# Generated by Django 4.2.7 on 2023-11-14 06:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_lga"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lga",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="lga",
            name="district",
        ),
    ]
