# Generated by Django 4.2.7 on 2023-12-12 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_auto_load_lgas"),
        ("main", "0014_documentcategory_documentdescriptor_and_more"),
    ]

    operations = []
