# Generated by Django 4.2.7 on 2023-12-04 08:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main", "0013_neighbourrole_neighbour"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "approval_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("endorsement", "Endorsement"),
                            ("approval", "Approval"),
                            ("endorsement_or_approval", "Endorsement/Approval"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "land_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("shire", "Shire"),
                            ("owner", "Owner"),
                            ("other", "Other Lands"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("approver", models.CharField(blank=True, max_length=255, null=True)),
                ("has_additional_permissions", models.BooleanField(default=False)),
                (
                    "is_required_for_operational_area",
                    models.BooleanField(default=False),
                ),
                (
                    "is_required_for_operational_plan",
                    models.BooleanField(default=False),
                ),
            ],
            options={
                "verbose_name": "Legal/Approval",
                "verbose_name_plural": "Legal/Approvals",
            },
        ),
        migrations.CreateModel(
            name="ModelLegalApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("text_as_approval", models.TextField(blank=True, null=True)),
                ("text_remove_justification", models.TextField(blank=True, null=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_type",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "legal_approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modellegalapprovals",
                        to="legalapproval.legalapproval",
                    ),
                ),
                (
                    "lga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modellegalapprovals",
                        to="main.lga",
                        verbose_name="Shire/LGA",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Legal/Approvals",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="legalapprov_content_6e96ad_idx",
                    )
                ],
            },
        ),
    ]
