# Generated by Django 4.2.7 on 2023-12-05 07:10

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("legalapproval", "0001_initial"),
    ]


    operations = [
        migrations.AddField(
            model_name="legalapproval",
            name="name",
            field=models.CharField(default="default-name", max_length=255, null=True),
            preserve_default=False,
        ),
    ]
