# Generated by Django 4.2.7 on 2023-12-05 07:30

from django.db import migrations


def populate_default_name(apps, schema_editor):
    LegalApproval = apps.get_model("legalapproval", "LegalApproval")
    default_idx = 0
    for row in LegalApproval.objects.all():
        row.name = f"default-name-{default_idx}"
        row.save()
        default_idx += 1


class Migration(migrations.Migration):
    dependencies = [
        ("legalapproval", "0002_legalapproval_name"),
    ]

    operations = [
        migrations.RunPython(
            populate_default_name, reverse_code=migrations.RunPython.noop
        ),
    ]
