# Generated by Django 4.2.7 on 2023-12-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legalapproval", "0003_auto_20231205_1530"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legalapproval",
            name="name",
            field=models.CharField(default="default-name", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
