# Generated by Django 4.2.7 on 2023-12-06 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("legalapproval", "0004_auto_20231205_1530"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modellegalapproval",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_type_legal_approval",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.CreateModel(
            name="ModelRequiredApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legal_approval_name", models.CharField(max_length=255)),
                ("is_required", models.BooleanField(default=False)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_type_required_approval",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Required Approvals",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="legalapprov_content_d04cc8_idx",
                    )
                ],
            },
        ),
    ]
