# Generated by Django 4.2.7 on 2023-12-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legalapproval", "0005_alter_modellegalapproval_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelrequiredapproval",
            name="display_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
