# Generated by Django 4.2.7 on 2023-12-07 01:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("legalapproval", "0006_modelrequiredapproval_display_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="modelrequiredapproval",
            unique_together={("legal_approval_name", "content_type", "object_id")},
        ),
    ]
