# Generated by Django 4.2.7 on 2023-12-08 02:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("legalapproval", "0008_lawfulauthority_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modellegalapproval",
            name="fauna_authority_to_take",
        ),
        migrations.RemoveField(
            model_name="modellegalapproval",
            name="flora_authority_to_take",
        ),
    ]
