# Generated by Django 4.2.7 on 2023-12-08 06:55

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "legalapproval",
            "0009_remove_modellegalapproval_fauna_authority_to_take_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("lodgement_date", models.DateField(blank=True, null=True)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
