# Generated by Django 4.2.7 on 2023-12-08 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("legalapproval", "0010_otherapproval"),
        (
            "operationalplanning",
            "0070_alter_operationalplan_fauna_authority_to_take_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="LawfulAuthority",
        ),
    ]
