# Generated by Django 4.2.7 on 2023-12-08 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("legalapproval", "0011_delete_lawfulauthority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otherapproval",
            name="created",
        ),
        migrations.RemoveField(
            model_name="otherapproval",
            name="display_name",
        ),
        migrations.RemoveField(
            model_name="otherapproval",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="otherapproval",
            name="name",
        ),
        migrations.CreateModel(
            name="DisturbanceApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disturbanceapplication_approvals",
                        to="legalapproval.otherapproval",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disturbanceapplication_proposals",
                        to="legalapproval.otherapproval",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuthorityToTake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authoritytotake_applications",
                        to="legalapproval.otherapproval",
                    ),
                ),
                (
                    "issuance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authoritytotake_issuances",
                        to="legalapproval.otherapproval",
                    ),
                ),
            ],
        ),
    ]
