# Generated by Django 4.2.7 on 2023-12-11 08:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "legalapproval",
            "0014_remove_modellegalapproval_disturbance_approval_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disturbanceapplication",
            options={
                "verbose_name": "Disturbance Application",
                "verbose_name_plural": "Disturbance Applications",
            },
        ),
    ]
