# Generated by Django 4.2.8 on 2023-12-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legalapproval", "0015_alter_disturbanceapplication_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authoritytotake",
            options={
                "verbose_name": "Authority to take",
                "verbose_name_plural": "Authorities to take",
            },
        ),
        migrations.AddField(
            model_name="otherapproval",
            name="reference_number",
            field=models.CharField(blank=True, editable=False, max_length=9, null=True),
        ),
    ]
