# Generated by Django 4.2.8 on 2023-12-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legalapproval", "0016_alter_authoritytotake_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otherapproval",
            name="reference_number",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
