# Generated by Django 4.2.8 on 2023-12-15 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("legalapproval", "0017_alter_otherapproval_reference_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authoritytotake",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_proposals",
                to="legalapproval.otherapproval",
            ),
        ),
        migrations.AlterField(
            model_name="authoritytotake",
            name="issuance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_approvals",
                to="legalapproval.otherapproval",
            ),
        ),
        migrations.AlterField(
            model_name="disturbanceapplication",
            name="approval",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_approvals",
                to="legalapproval.otherapproval",
            ),
        ),
        migrations.AlterField(
            model_name="disturbanceapplication",
            name="proposal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_proposals",
                to="legalapproval.otherapproval",
            ),
        ),
    ]
