# Generated by Django 4.2.8 on 2023-12-15 07:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("legalapproval", "0018_alter_authoritytotake_application_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authoritytotake",
            options={
                "verbose_name": "Authority to Take",
                "verbose_name_plural": "Authorities to Take",
            },
        ),
    ]
