# Generated by Django 4.2.6 on 2023-10-16 03:01

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main", "0008_alter_district_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="BurnPlanUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[
                            ("draft", "Draft"),
                            ("current", "Current"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, editable=False, max_length=9, null=True
                    ),
                ),
                (
                    "polygon",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "active_from",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2023)]
                    ),
                ),
                (
                    "active_to",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2023)]
                    ),
                ),
                ("allow_recording_of_hectares", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BurnPlanUnitDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "burn_plan_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="burnplanning.burnplanunit",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.district"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Burn Plan Unit Districts",
                "unique_together": {("burn_plan_unit", "district")},
            },
        ),
        migrations.AddField(
            model_name="burnplanunit",
            name="district",
            field=models.ManyToManyField(
                editable=False,
                through="burnplanning.BurnPlanUnitDistrict",
                to="main.district",
            ),
        ),
    ]
