# Generated by Django 4.2.6 on 2023-10-16 04:03

import django.core.validators
from django.db import migrations
import govapp.apps.main.models


class Migration(migrations.Migration):
    dependencies = [
        ("burnplanning", "0002_alter_burnplanunit_active_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="burnplanunit",
            name="active_from",
            field=govapp.apps.main.models.YearField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2023),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="burnplanunit",
            name="active_to",
            field=govapp.apps.main.models.YearField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2023),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
    ]
