# Generated by Django 4.2.6 on 2023-10-16 04:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import govapp.apps.main.models
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("burnplanning", "0003_alter_burnplanunit_active_from_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Justification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, editable=False, max_length=9, null=True
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OutputLeaderType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, editable=False, max_length=9, null=True
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, editable=False, max_length=9, null=True
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Purpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, editable=False, max_length=9, null=True
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, editable=False, max_length=9, null=True
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OutputLeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, editable=False, max_length=9, null=True
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                (
                    "indicative_treatement_year",
                    govapp.apps.main.models.YearField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(2023),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                (
                    "revised_indicative_treatment_year",
                    govapp.apps.main.models.YearField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(2023),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                (
                    "preferred_season",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("autumn", "Autumn"),
                            ("winter", "Winter"),
                            ("spring", "Spring"),
                            ("summer", "Summer"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="burnplanning.outputleadertype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BurnPlanElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[
                            ("draft", "Draft"),
                            ("current", "Current"),
                            ("discarded", "discarded"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, editable=False, max_length=9, null=True
                    ),
                ),
                (
                    "year",
                    govapp.apps.main.models.YearField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(2023),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                (
                    "last_relevant_treatment_year",
                    govapp.apps.main.models.YearField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(2023),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                (
                    "indicative_treatment_year",
                    govapp.apps.main.models.YearField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(2023),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                (
                    "revised_indicative_treatment_year",
                    govapp.apps.main.models.YearField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(2023),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                (
                    "return_interval",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "preferred_season",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("autumn", "Autumn"),
                            ("winter", "Winter"),
                            ("spring", "Spring"),
                            ("summer", "Summer"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "justification",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="burnplanning.justification",
                    ),
                ),
                (
                    "output_leaders",
                    models.ManyToManyField(to="burnplanning.outputleader"),
                ),
                ("programs", models.ManyToManyField(to="burnplanning.program")),
                ("purposes", models.ManyToManyField(to="burnplanning.purpose")),
                (
                    "treatment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="burnplanning.treatment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
