# Generated by Django 4.2.6 on 2023-10-16 04:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "burnplanning",
            "0004_justification_outputleadertype_program_purpose_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="justification",
            name="reference_number",
        ),
        migrations.RemoveField(
            model_name="outputleader",
            name="reference_number",
        ),
        migrations.RemoveField(
            model_name="outputleadertype",
            name="reference_number",
        ),
        migrations.RemoveField(
            model_name="program",
            name="reference_number",
        ),
        migrations.RemoveField(
            model_name="purpose",
            name="reference_number",
        ),
        migrations.RemoveField(
            model_name="treatment",
            name="reference_number",
        ),
    ]
