# Generated by Django 4.2.6 on 2023-10-16 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("burnplanning", "0005_remove_justification_reference_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="burnplanelement",
            name="burn_plan_unit",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="burnplanning.burnplanunit",
            ),
        ),
    ]
