# Generated by Django 4.2.6 on 2023-10-16 04:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("burnplanning", "0006_burnplanelement_burn_plan_unit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="burnplanunit",
            old_name="district",
            new_name="districts",
        ),
    ]
