# Generated by Django 4.2.6 on 2023-10-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("burnplanning", "0007_rename_district_burnplanunit_districts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outputleader",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
