# Generated by Django 4.2.6 on 2023-10-16 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("burnplanning", "0008_alter_outputleader_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="burnplanelement",
            name="output_leaders",
        ),
        migrations.DeleteModel(
            name="OutputLeader",
        ),
    ]
