# Generated by Django 4.2.6 on 2023-10-16 06:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import govapp.apps.main.models
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("burnplanning", "0009_remove_burnplanelement_output_leaders_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutputLeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("archived", models.BooleanField(default=False)),
                (
                    "indicative_treatement_year",
                    govapp.apps.main.models.YearField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(2023),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                (
                    "revised_indicative_treatment_year",
                    govapp.apps.main.models.YearField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(2023),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                (
                    "preferred_season",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("autumn", "Autumn"),
                            ("winter", "Winter"),
                            ("spring", "Spring"),
                            ("summer", "Summer"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "burn_plan_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="output_leaders",
                        to="burnplanning.burnplanelement",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="burnplanning.outputleadertype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
