# Generated by Django 4.2.6 on 2023-11-01 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_lga"),
        ("burnplanning", "0010_outputleader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="burnplanunitdistrict",
            name="burn_plan_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="burnplanunitdistricts",
                to="burnplanning.burnplanunit",
            ),
        ),
        migrations.AlterField(
            model_name="burnplanunitdistrict",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="burnplanunitdistricts",
                to="main.district",
            ),
        ),
    ]
