# Generated by Django 4.2.8 on 2023-12-19 01:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("burnplanning", "0011_alter_burnplanunitdistrict_burn_plan_unit_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outputleader",
            old_name="indicative_treatement_year",
            new_name="indicative_treatment_year",
        ),
    ]
