# Generated by Django 4.2.8 on 2023-12-19 03:47

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "burnplanning",
            "0012_rename_indicative_treatement_year_outputleader_indicative_treatment_year",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="burnplanelement",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("draft", "Draft"),
                    ("current", "Current"),
                    ("discarded", "Discarded"),
                    ("retired", "Retired"),
                ],
                default="draft",
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="burnplanunit",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("draft", "Draft"),
                    ("current", "Current"),
                    ("discarded", "Discarded"),
                    ("retired", "Retired"),
                ],
                default="draft",
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
    ]
