# Generated by Django 4.2.9 on 2024-02-06 04:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("burnplanning", "0014_alter_burnplanelement_justification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="burnplanunit",
            name="return_interval",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
