# Generated by Django 4.2.11 on 2024-03-11 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("burnplanning", "0018_burnplanelement_seeking_endorsement_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="burnplanunit",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
