# Generated by Django 4.2.6 on 2023-10-31 02:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import govapp.apps.main.models
import model_utils.fields
import protected_media.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("risk", "0001_initial"),
        ("burnplanning", "0010_outputleader"),
        ("main", "0010_lga"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalAreaApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("approver", models.CharField(blank=True, max_length=255, null=True)),
                ("can_provide_evidence", models.BooleanField(default=False)),
                (
                    "file_as_approval",
                    protected_media.models.ProtectedFileField(
                        storage=protected_media.models.ProtectedFileSystemStorage(),
                        upload_to=govapp.apps.main.models.file_upload_location,
                    ),
                ),
                ("text_as_approval", models.TextField(blank=True, null=True)),
                ("text_remove_justification", models.TextField(blank=True, null=True)),
                (
                    "lga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.lga",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OperationalArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, editable=False, max_length=9, null=True
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "polygon",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "linestring",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "operation_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("burn_priority", models.IntegerField(blank=True, null=True)),
                ("contentious_burn", models.BooleanField(default=False)),
                ("contentious_rationale", models.TextField(blank=True, null=True)),
                (
                    "operational_area_different_from_bpu_rationale",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "approvals",
                    models.ManyToManyField(
                        blank=True,
                        related_name="operational_areas",
                        to="operationalarea.operationalareaapproval",
                    ),
                ),
                (
                    "burn_plan_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_areas",
                        to="burnplanning.burnplanunit",
                    ),
                ),
                (
                    "risk_factors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="operational_areas",
                        to="risk.riskfactor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
