# Generated by Django 4.2.6 on 2023-10-31 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("risk", "0004_remove_riskfactor_contributing_factor_and_more"),
        ("operationalarea", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalAreaRiskFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("values_affected", models.TextField(blank=True, null=True)),
                (
                    "contributing_factor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="risk_factors",
                        to="risk.contributingfactor",
                    ),
                ),
                (
                    "risk_factor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="risk.riskfactor",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="operationalarea",
            name="risk_factors",
            field=models.ManyToManyField(
                blank=True,
                related_name="operational_areas",
                to="operationalarea.operationalareariskfactor",
            ),
        ),
    ]
