# Generated by Django 4.2.6 on 2023-11-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operationalarea", "0004_alter_operationalareaapproval_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalapproval",
            name="approval_type",
            field=models.CharField(
                blank=True,
                choices=[("approval", "Approval"), ("endorsement", "Endorsement")],
                max_length=255,
                null=True,
            ),
        ),
    ]
