# Generated by Django 4.2.6 on 2023-11-07 03:01

from django.db import migrations, models
import govapp.apps.main.models
import protected_media.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "operationalarea",
            "0006_rename_can_provide_evidence_legalapproval_has_additional_permissions",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="legalapproval",
            name="file_as_approval",
        ),
        migrations.RemoveField(
            model_name="legalapproval",
            name="text_as_approval",
        ),
        migrations.RemoveField(
            model_name="legalapproval",
            name="text_remove_justification",
        ),
        migrations.AddField(
            model_name="operationalareaapproval",
            name="file_as_approval",
            field=protected_media.models.ProtectedFileField(
                blank=True,
                null=True,
                storage=protected_media.models.ProtectedFileSystemStorage(),
                upload_to=govapp.apps.main.models.file_upload_location,
            ),
        ),
        migrations.AddField(
            model_name="operationalareaapproval",
            name="text_as_approval",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationalareaapproval",
            name="text_remove_justification",
            field=models.TextField(blank=True, null=True),
        ),
    ]
