# Generated by Django 4.2.6 on 2023-11-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operationalarea", "0010_alter_operationalareaapproval_lga"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationalarea",
            name="mitigation_purpose",
            field=models.CharField(
                choices=[
                    ("burning", "Burning"),
                    ("mechanical", "Stand-alone Mechanical"),
                ],
                default="burning",
                max_length=255,
            ),
        ),
    ]
