# Generated by Django 4.2.6 on 2023-11-08 01:41

import django.core.validators
from django.db import migrations
import govapp.apps.main.models


class Migration(migrations.Migration):
    dependencies = [
        ("operationalarea", "0011_alter_operationalarea_mitigation_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalarea",
            name="year",
            field=govapp.apps.main.models.YearField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2023),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
    ]
