# Generated by Django 4.2.6 on 2023-11-08 03:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("burnplanning", "0011_alter_burnplanunitdistrict_burn_plan_unit_and_more"),
        ("operationalarea", "0012_operationalarea_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalAreaPurpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "operational_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operationalareapurposes",
                        to="operationalarea.operationalarea",
                    ),
                ),
                (
                    "purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operationalareapurposes",
                        to="burnplanning.purpose",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OperationalAreaProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "operational_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operationalareaprograms",
                        to="operationalarea.operationalarea",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operationalareaprograms",
                        to="burnplanning.program",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="operationalarea",
            name="program",
            field=models.ManyToManyField(
                editable=False,
                related_name="operational_areas",
                through="operationalarea.OperationalAreaProgram",
                to="burnplanning.program",
            ),
        ),
        migrations.AddField(
            model_name="operationalarea",
            name="purpose",
            field=models.ManyToManyField(
                editable=False,
                related_name="operational_areas",
                through="operationalarea.OperationalAreaPurpose",
                to="burnplanning.purpose",
            ),
        ),
    ]
