# Generated by Django 4.2.6 on 2023-10-13 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AircraftRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AircraftType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IgnitionMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AviationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, editable=False, max_length=9, null=True
                    ),
                ),
                ("datetime_requested", models.DateTimeField()),
                ("duration", models.DurationField()),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[
                            (0, "Draft"),
                            (1, "Submitted"),
                            (2, "Declined"),
                            (3, "Approved"),
                        ],
                        default=0,
                        max_length=100,
                        no_check_for_status=True,
                    ),
                ),
                ("decision_datetime", models.DateTimeField(blank=True, null=True)),
                ("decision_text", models.TextField(blank=True, null=True)),
                (
                    "aircraft_registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aviation.aircraftregistration",
                    ),
                ),
                (
                    "aircraft_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aviation.aircrafttype",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decision_made_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aviation_request_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ignition_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aviation.ignitionmethod",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
