# Generated by Django 4.2.6 on 2023-10-13 04:22

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("aviation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aviationrequest",
            name="status_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                monitor="status",
                verbose_name="status changed",
            ),
        ),
        migrations.AlterField(
            model_name="aviationrequest",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("declined", "Declined"),
                    ("approved", "Approved"),
                ],
                default="draft",
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
    ]
