# Generated by Django 4.2.6 on 2023-10-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aviation", "0003_remove_aviationrequest_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="aviationrequest",
            name="duration",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
