# Generated by Django 4.2.6 on 2023-10-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aviation", "0004_aviationrequest_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aviationrequest",
            name="duration",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The duration in hours (e.g. 1.5)",
                max_digits=10,
            ),
        ),
    ]
