# Generated by Django 4.2.6 on 2023-10-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_file_delete_modelfile"),
        ("aviation", "0005_alter_aviationrequest_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="aviationrequest",
            name="decision_files",
            field=models.ManyToManyField(to="main.file"),
        ),
    ]
