# Generated by Django 4.2.6 on 2023-10-13 06:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aviation", "0006_aviationrequest_decision_files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aviationrequest",
            name="decision_files",
        ),
    ]
