# Generated by Django 4.2.6 on 2023-10-13 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aviation", "0008_alter_aircraftregistration_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AviationRequest",
        ),
    ]
