# Generated by Django 4.2.6 on 2023-10-13 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0005_alter_district_display_name_and_more"),
        ("aviation", "0009_delete_aviationrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="AviationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("declined", "Declined"),
                            ("approved", "Approved"),
                        ],
                        default="draft",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, editable=False, max_length=9, null=True
                    ),
                ),
                ("datetime_requested", models.DateTimeField()),
                (
                    "duration",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The duration in hours (e.g. 1.5)",
                        max_digits=10,
                    ),
                ),
                ("decision_datetime", models.DateTimeField(blank=True, null=True)),
                ("decision_text", models.TextField(blank=True, null=True)),
                (
                    "aircraft_registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aviation.aircraftregistration",
                    ),
                ),
                (
                    "aircraft_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aviation.aircrafttype",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decision_made_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aviation_request_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.district"
                    ),
                ),
                (
                    "ignition_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aviation.ignitionmethod",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.region"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
