# Generated by Django 4.2.7 on 2023-11-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescriptiondetails", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BurnArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Area to be burnt",
                "verbose_name_plural": "Areas to be burnt",
            },
        ),
        migrations.CreateModel(
            name="FfdiRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Forest Fire Danger Index (FFDI)",
                "verbose_name_plural": "Forest Fire Danger Indices (FFDI)",
            },
        ),
        migrations.CreateModel(
            name="GfdiRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Grass Fire Danger Index (GFDI)",
                "verbose_name_plural": "Grass Fire Danger Indices (GFDI)",
            },
        ),
        migrations.CreateModel(
            name="GlcRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Ground Level Concentration??? (GLC)",
                "verbose_name_plural": "Ground Level Concentrations??? (GLC)",
            },
        ),
        migrations.CreateModel(
            name="PmcRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Profile Fuel Moisture Content (PMC)",
                "verbose_name_plural": "Profile Fuel Moisture Contents (PMC)",
            },
        ),
        migrations.CreateModel(
            name="RhRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Relative Humidity (RH)",
                "verbose_name_plural": "Relative Humidities (RH)",
            },
        ),
        migrations.CreateModel(
            name="RosRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Rate of Spread (ROS)",
                "verbose_name_plural": "Rates of Spread (ROS)",
            },
        ),
        migrations.CreateModel(
            name="ScorchHeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Scorch Height",
                "verbose_name_plural": "Scorch Heights",
            },
        ),
        migrations.CreateModel(
            name="Sdi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Soil Dryness Index (SDI)",
                "verbose_name_plural": "Soil Dryness Index (SDI)",
            },
        ),
        migrations.CreateModel(
            name="SmcRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Surface Fuel Moisture Content (SMC)",
                "verbose_name_plural": "Surface Fuel Moisture Contents (SMC)",
            },
        ),
        migrations.CreateModel(
            name="TemperatureRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Temperature",
                "verbose_name_plural": "Temperatures",
            },
        ),
        migrations.CreateModel(
            name="WindDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Wind Direction",
                "verbose_name_plural": "Wind Directions",
            },
        ),
        migrations.CreateModel(
            name="WindSpeedRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Wind Speed",
                "verbose_name_plural": "Wind Speeds",
            },
        ),
    ]
