# Generated by Django 4.2.7 on 2023-11-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescriptiondetails", "0003_fueltype_fuel_type_layer"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicableFuelTypeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Applicable Fuel Type Detail",
                "verbose_name_plural": "Applicable Fuel Type Details",
            },
        ),
        migrations.AlterModelOptions(
            name="burnarea",
            options={},
        ),
        migrations.AlterModelOptions(
            name="ffdirange",
            options={},
        ),
        migrations.AlterModelOptions(
            name="gfdirange",
            options={},
        ),
        migrations.AlterModelOptions(
            name="glcrange",
            options={},
        ),
        migrations.AlterModelOptions(
            name="pmcrange",
            options={},
        ),
        migrations.AlterModelOptions(
            name="rhrange",
            options={},
        ),
        migrations.AlterModelOptions(
            name="rosrange",
            options={},
        ),
        migrations.AlterModelOptions(
            name="scorchheight",
            options={},
        ),
        migrations.AlterModelOptions(
            name="sdi",
            options={},
        ),
        migrations.AlterModelOptions(
            name="smcrange",
            options={},
        ),
        migrations.AlterModelOptions(
            name="temperaturerange",
            options={},
        ),
        migrations.AlterModelOptions(
            name="winddirection",
            options={},
        ),
        migrations.AlterModelOptions(
            name="windspeedrange",
            options={},
        ),
    ]
