# Generated by Django 4.2.8 on 2023-12-18 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prescriptiondetails", "0007_applicablefueltypeprescriptiondetail_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicablefueltypeprescriptiondetail",
            options={
                "verbose_name": "Fuel Type - Applicable Prescription Detail",
                "verbose_name_plural": "Fuel Type - Applicable Prescription Details",
            },
        ),
    ]
