# Generated by Django 4.2.10 on 2024-02-29 01:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communicationslogdocument",
            name="user",
        ),
    ]
