# Generated by Django 4.2.10 on 2024-03-06 01:56

from django.db import migrations
import govapp.apps.logs.models
import protected_media.models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0002_remove_communicationslogdocument_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communicationslogdocument",
            name="file",
            field=protected_media.models.ProtectedFileField(
                storage=protected_media.models.ProtectedFileSystemStorage(),
                upload_to=govapp.apps.logs.models.communications_log_document_upload_location,
            ),
        ),
    ]
